# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ master ]
    paths-ignore: [README.md]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    uses: XenosLu/xenoslib/.github/workflows/lint.yml@master

  tests:
    needs: lint
    uses: XenosLu/xenoslib/.github/workflows/tests.yml@master

  publish:
    needs: tests
    uses: XenosLu/xenoslib/.github/workflows/publish.yml@master
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      WEBHOOK: ${{ secrets.WEBHOOK }}

  # 新增失败通知作业
  notify-failure:
    needs: [lint, tests, publish]  # 依赖所有关键作业
    if: failure()  # 任意一个依赖作业失败时触发
    runs-on: ubuntu-latest
    steps:
      - name: use slack Webhook send notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "text": " "xenoslib $(python3 setup.py --version) failed.\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }' \
            "${{ secrets.WEBHOOK }}"
