# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ master ]
    paths-ignore: [README.md]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Lint with flake8
        id: lint1
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics || echo "::set-output name=failure::true"
      - name: Try Format
        if: steps.lint1.outputs.failure == 'true'
        run: |
          git config --local user.email "xenos.lu@gmail.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          pip install black
          black -S -l 100 .
          git commit -a -m 'Auto Format with Black'
          git push
      - name: Lint with flake8 after format
        if: steps.lint1.outputs.failure == 'true'
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

  tests:
    needs: lint
    uses: XenosLu/xenoslib/.github/workflows/tests.yml@master

  publish:
    needs: tests
    uses: XenosLu/xenoslib/.github/workflows/publish.yml@master
    secrets:
      PYPI_API_TOKEN : ${{ secrets.PYPI_API_TOKEN  }}
