# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ master ]
    paths-ignore: [README.md]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:
    uses: XenosLu/xenoslib/.github/workflows/lint.yml@master

  tests:
    needs: lint
    uses: XenosLu/xenoslib/.github/workflows/tests.yml@master

  publish:
    needs: tests
    uses: XenosLu/xenoslib/.github/workflows/publish.yml@master
    secrets:
      PYPI_API_TOKEN : ${{ secrets.PYPI_API_TOKEN  }}
      WEBHOOK : ${{ secrets.WEBHOOK  }}
