# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python Package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  workflow_call:
    secrets:
      WEBHOOK:
        required: true
      PYPI_API_TOKEN:
        required: true

jobs:
  tag:

    runs-on: ubuntu-latest
    outputs: 
      tagged: ${{ steps.tag.outputs.tagged }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Try tag
        id: tag
        run: |
          git config --local user.email "xenos.lu@gmail.com"
          git config --local user.name "${{ github.actor }}"
          git tag v$(python3 setup.py --version)
          git push --tags && echo "tagged=true" >> $GITHUB_OUTPUT || echo skipped.
  publish:

    runs-on: ubuntu-latest
    needs: tag
    if: needs.tag.outputs.tagged == 'true'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Send message
        run: |
          curl -X POST -H "Content-type: application/json" --data "{\"text\":\"xenoslib $(python3 setup.py --version) published\"}" ${{ secrets.WEBHOOK }}
 